export const ZONAS_HORARIAS = [
    { value: "America/Guayaquil", label: "Ecuador (Guayaquil)" },
    { value: "America/Lima", label: "Perú (Lima)" },
    { value: "America/Bogota", label: "Colombia (Bogotá)" },
    { value: "America/Mexico_City", label: "México (Ciudad de México)" },
    { value: "America/New_York", label: "Estados Unidos (Nueva York)" },
    { value: "America/Los_Angeles", label: "Estados Unidos (Los Ángeles)" },
    { value: "America/Sao_Paulo", label: "Brasil (São Paulo)" },
    { value: "America/Argentina/Buenos_Aires", label: "Argentina (Buenos Aires)" },
    { value: "Europe/Madrid", label: "España (Madrid)" },
    { value: "Europe/London", label: "Reino Unido (Londres)" },
    { value: "Europe/Paris", label: "Francia (París)" },
    { value: "Africa/Cairo", label: "Egipto (El Cairo)" },
    { value: "Asia/Dubai", label: "Emiratos Árabes Unidos (Dubái)" },
    { value: "Asia/Kolkata", label: "India (Calcuta)" },
    { value: "Asia/Shanghai", label: "China (Shanghái)" },
    { value: "Asia/Tokyo", label: "Japón (Tokio)" },
    { value: "Asia/Seoul", label: "Corea del Sur (Seúl)" },
    { value: "Australia/Sydney", label: "Australia (Sídney)" },
    { value: "Pacific/Auckland", label: "Nueva Zelanda (Auckland)" },
    { value: "UTC", label: "UTC" },
];